import express from 'express';
import { authenticate, requireRole } from '../middleware/auth.js';
import * as fc from '../controllers/facultyController.js';
const router = express.Router();
router.use(authenticate, requireRole('faculty', 'admin'));
router.get('/dashboard', fc.getFacultyDashboard);
router.get('/classes', fc.getMyClasses);
router.get('/pending-alerts', fc.getPendingAlerts);
router.post('/send-alert', fc.sendStudentAlert);
router.get('/class/:id/summary', fc.getClassSummary);
router.get('/class/:id/heatmap', fc.getClassHeatmap);
router.get('/class/:id/report/pdf', fc.downloadClassReport);
router.get('/student/:id/full-profile', fc.getStudentFullProfile);
router.get('/class/:id/voice-summary', fc.getClassVoiceSummary);
router.get('/effectiveness', fc.getFacultyEffectiveness);
router.get('/effectiveness-history', fc.getFacultyEffectivenessHistory);
export default router;
